### ISSUE TITLE
Homebrew aliases problem on linux (Ubuntu)

### ISSUE THREAD

**Issue by merencia** [caarlos0/dotfiles.zsh#1]
When I start zsh on Ubuntu I got this message:
`/home/lucas/.dotfiles/homebrew/aliases.zsh:1 condition expected:  not`

But I can use normally...

**Comment by caarlos0** [comment]
Sorry, bad exp. Should be fixed now.

**Comment by merencia** [comment]
Working like a charm!

Thanks!

**Comment by caarlos0** [comment]
Nice!
