### ISSUE TITLE
Update readme screenshots

### ISSUE THREAD

**Issue by caarlos0** [caarlos0/dotfiles.zsh#108]
They are outdated..

**Comment by samimb** [comment]
What font is that in the screenshot?

**Comment by caarlos0** [comment]
@samimb Source Code PRO:  https://github.com/adobe-fonts/source-code-pro

**Comment by samimb** [comment]
It's really strange, my source-code pro looks different. 
It's more spaced. 
<img width="762" alt="screen shot 2015-10-22 at 12 56 34" src="https://cloud.githubusercontent.com/assets/4834107/10663511/5998138e-78bc-11e5-818e-8c58ba7b1bf4.png">

**Comment by samimb** [comment]
Are you using iterm2? What does your font settings look like?

**Comment by caarlos0** [comment]
@samimb now it look like this: 
<img width="1036" alt="screen shot 2015-10-22 at 8 50 22 pm" src="https://cloud.githubusercontent.com/assets/245435/10680439/92b4736e-78fe-11e5-8788-184059c0629d.png">

**Comment by caarlos0** [comment]
@samimb actually, now I'm using Hack...
