### ISSUE TITLE
iTerm config

### ISSUE THREAD

**Issue by julienmiclo** [caarlos0/dotfiles.zsh#184]
Hi, 
i don't know why but i can't load preset for iterm2. In field "Load preferences from a custom folder or URL" 
There's only "/iterm" and orange warning icon? What i can do for solved this?

**Comment by caarlos0** [comment]
Hi @Amstramgram ,

thanks for reporting this.

It's probably a bug in https://github.com/caarlos0/dotfiles/blob/master/iterm/install.sh#L3  , I think `$ZSH` is not set in that particular time.

Can you change it to `~/.dotfiles/iterm2` to test if it works?

If so, I'll fix the install to deal with this issue properly.

**Comment by julienmiclo** [comment]
I added the complete path not with ~ "Users/name/.dotfiles/iterm". I have green check but i must see something different in iTerm? How i can have the theme from screenshot?
I have other question if i want add some alias like this: alias ll="ls -la" or git alias, where i put this line? system/aliases.zsh?
Thank you.

**Comment by caarlos0** [comment]
closing and opening the terminal had no effect?

you can put custom aliases and setting in `~/.localrc` (which I should probably document)

**Comment by julienmiclo** [comment]
No effect when i close and open the terminal.
i'm rookie in dotfiles system for someone who know, it's obviously, i think.

**Comment by caarlos0** [comment]
@Amstramgram can you paste here some screenshots of your terminal?

**Comment by julienmiclo** [comment]
![Screenshots](https://cloud.githubusercontent.com/assets/6685969/14316550/efd3cfbc-fc03-11e5-8089-2b09a32b2383.png)
I go try to restart my computer maybe solve this.

**Comment by caarlos0** [comment]
@Amstramgram I think you need to run `brew install zsh && chsh -s $(which zsh)`, then close and open your terminal..

the iterm configs are fine, is just that you still running bash...

**Comment by julienmiclo** [comment]
ok i think now it's ok.; i run your command, restart terminal and restart computer.
![run_term](https://cloud.githubusercontent.com/assets/6685969/14318548/ae0d86ea-fc0d-11e5-9c3e-c6f8e6c58bf8.png)

Thank you for your time.

**Comment by caarlos0** [comment]
so, it's working now?

**Comment by julienmiclo** [comment]
I found a solution, i don't know how but it's working. I change "Login shell" in advanced options in users&groups "/bin/bash" by "/bin/zsh" 

Thank you !

**Comment by caarlos0** [comment]
Oh, the iterm config should have set this up.

The login shell that I use is `/usr/local/bin/zsh --login`
