### ISSUE TITLE
Speed report

### ISSUE THREAD

**Issue by caarlos0** [caarlos0/dotfiles.zsh#198]
Time to time, I intend to run a simple speed test to see how it is doing, and improve what I can.

The command used to that is `for i in $(seq 1 10); do /usr/bin/time zsh -i -c exit; done`

This is what was done so far:
- #189 
- #190 
- #191
#190 and #189 were better documented in [this blog post](http://carlosbecker.com/posts/speeding-up-zsh).

**Comment by leoj3n** [comment]
Didn't know Zsh had a really nice profiling module; I've found it to be very useful. Hadn't seen you mention it in your blog posts or here, so wanted to share `zsh/zprof` with you incase it's news to you as well:

```
zmodload zsh/zprof
code-to-profile
zprof
```

http://zsh.sourceforge.net/Doc/Release/Zsh-Modules.html#The-zsh_002fzprof-Module

**Comment by caarlos0** [comment]
Yeah, I tried to use it, didn't gave me useful information...

Will try again later maybe :) 

Thanks

**Comment by ghost** [comment]
Thanks for the configs ❤️

**Comment by caarlos0** [comment]
@fgbreel 🍻

**Comment by ahmedre** [comment]
super minor, but thought i'd share - i found that changing `$(brew --prefix)` directly with `/usr/local` for sourcing `grc.bashrc` saved me ~30ms on the load time in the grc configuration.

**Comment by caarlos0** [comment]
@ahmedre yeah, `brew` is pretty slow
