### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by leoj3n** [caarlos0/dotfiles.zsh#256]
Why did you remove the check [here](https://github.com/caarlos0/dotfiles/commit/817a8e5123287a99821e838ff2334068f546d339#diff-39ea1a7bd84070093a8b2fc4b0aaea7aL6) and what does `eval` with `rbenv $@` do?

**Comment by caarlos0** [comment]
I could possible leave the `if` statement.

The eval loads the rbenv needed stuff. It takes like ~0.2 secs to run and rarely use it, so I mapped it into the into the `rbenv` function and call it when I need it...

**Comment by leoj3n** [comment]
Oh, okay gotcha, very nice!

You could possibly avoid calling eval every time with something like this clever little hack https://github.com/benvan/sandboxd

**Comment by caarlos0** [comment]
Nice, will take a look into that. Thanks!

**Comment by leoj3n** [comment]
Related (lazy loading): https://github.com/sorin-ionescu/prezto/pull/1186
