### ISSUE TITLE
improved speed

### ISSUE THREAD

**Issue by leoj3n** [caarlos0/dotfiles.zsh#257]
Why did you pull the `compinit` hack in https://github.com/caarlos0/dotfiles/commit/5a8584a7af1334856ee90d7f3e9fb9e87a565338#diff-1bd2fdbc6fa388782c5adbba1f0a2302L28

**Comment by caarlos0** [comment]
`compinit -C` is faster, but it doesn't update the completions whereas `compinit` does.

The hack was set to update it every day. Now that the dotfiles have auto-update and stuff, I added the full `compinit` to that (it runs every 2 hours on crontab), so it is actually more updated and possibly faster.

Check: #233 and https://github.com/caarlos0/dotfiles/pull/252/files#diff-0f26a6361229c5a213a239253c537f79R34

Is this a problem for you? If yes, why?

**Comment by leoj3n** [comment]
Thanks; that makes total sense after reading http://linux.die.net/man/1/zshcompsys
