### ISSUE TITLE
Have a way to ignore modules?

### ISSUE THREAD

**Issue by caarlos0** [caarlos0/dotfiles.zsh#278]
Maybe we should have a way to ignore modules? (a blacklist, in other terms)

**Comment by jscelza** [comment]
I actually have a way of doing this based on adding a DISABLED to the end of folder.  I am also wrapping the ability to use an uninstall.sh to remove the related packages.  If you would like me to pass this along let me know I will focus on closing it out in the next week.

**Comment by caarlos0** [comment]
Feel free to open a PR :)

**Comment by caarlos0** [comment]
I don't think I'll ever implement this.
