### ISSUE TITLE
Weird behavior of .config/terminator folder

### ISSUE THREAD

**Issue by cunhazera** [caarlos0/dotfiles.zsh#283]
I just don't know what is going on, but sometimes the `.config/terminator` folder appears again after I have deleted it. And it changes the terminator even if I have done the `KEEP_TERMINATOR=1`

Can you check it?

**Comment by cunhazera** [comment]
@caarlos0 the problem persists. Can you check this?

**Comment by caarlos0** [comment]
OK, so, you have your custom terminator config, have `KEEP_TERMINATOR=1` in `~/.localrc` and if you run `dot_update` it stills override the terminator config?

**Comment by cunhazera** [comment]
I kept my .config/terminator empty, and ran `dot_update` and now it's working. Thanks
