### ISSUE TITLE
Can't save NSUserDictionaryReplacementItems

### ISSUE THREAD

**Issue by lucaorio** [caarlos0/dotfiles.zsh#292]
Hey @caarlos0 ! It seems like the custom `NSUserDictionaryReplacementItems` aren't persistent.

```
defaults write -g NSUserDictionaryReplacementItems -array-add '{ on = 1; replace = dafuq; with = "\\U0ca0_\\U0ca0"; }'
```

A `defaults read NSGlobalDomain` shows that the array looks good, but after a logout it goes back to the original version (and the related preference pane is never updated).

Do you know how to solve this problem?

**Comment by caarlos0** [comment]
Hey @lucaorio, thanks for the report.

I did a little digging, found this: http://apple.stackexchange.com/questions/110776/writing-to-nsuserdictionaryreplacementitems-with-defaults

Seems pretty hacky to me, maybe I'll just take it out of the dotfiles (as they are not really useful shortcuts anyway :P).

Will do a little more digging and I'll get back to you soon.

Thanks again for the report!

**Comment by lucaorio** [comment]
You're more than welcome! :)

I noticed that the `NSUserDictionaryReplacementItems` are usually automatically synced by iCloud (unlike the real Keyboard shortcuts), so I wouldn't worry too much :D

**Comment by caarlos0** [comment]
Hey @lucaorio, I decided to just take it off.

It's not a really important feature anyways, and as you say, they go to iCloud, so there is no need for this I guess.

PR is #293.

Thanks again for reporting the issue.

Cheers!
