### ISSUE TITLE
How to remove dotfiles, and revert system back?

### ISSUE THREAD

**Issue by AlmasAskarbekov** [caarlos0/dotfiles.zsh#309]
Hey, I just installed this dotfiles on on mac os, but finally i don't like the whole changes the dotfiles made.
i didn't add original files to git.

**Comment by caarlos0** [comment]
Hi @Almax, I'm sorry you didn't like it.

There is no **automated** way of rolling back.

You can check the [bootstrap script](https://github.com/caarlos0/dotfiles/blob/master/script/bootstrap) though. It creates `.backup` files, so you can manually move them back over the dotfiles versions.

I don't know if this covers everything you wan't to revert, but, if not, you can open separated issues for each case, so we can add support for those so other people won't suffer the same :)

Cheers!
