### ISSUE TITLE
Migrate .bash_profile and .bashrc environment variables to .zshrc

### ISSUE THREAD

**Issue by negherbon** [caarlos0/dotfiles.zsh#327]
It's not a problem but seems to be better if the script migrate all my environment variables placed in .bash_profile or .bashrc to .zshrc file.

I passed a time trying understand why my environment variables in .bash_profile not loaded when i open my Terminal.app.

Thanks.

**Comment by caarlos0** [comment]
bashrc could have things that won't work on zsh for some reason, so this is not a safe thing to do.
