### ISSUE TITLE
 What theme to use?

### ISSUE THREAD

**Issue by gatspy** [caarlos0/dotfiles.zsh#329]
What is your theme for `iterm2`?

**Comment by caarlos0** [comment]
hi @gatspy, Snazzy, the one in the config file: https://github.com/caarlos0/dotfiles/blob/master/iterm/com.googlecode.iterm2.plist.example#L33

**Comment by caarlos0** [comment]
https://github.com/sindresorhus/iterm2-snazzy

**Comment by gatspy** [comment]
@caarlos0 
installed by `/script/bootstrap` why the  theme not effect ?
`$DOTFILES/item/com.googlecode.iterm2.plist.example`

**Comment by caarlos0** [comment]
possibly a bug then

**Comment by caarlos0** [comment]
can you try to execute `$DOTFILES/iterm/install.sh` please?

**Comment by gatspy** [comment]
after executing the above command good.
i do not know what is the reason, thanks.
