### ISSUE TITLE
Issues autoupdating

### ISSUE THREAD

**Issue by insuusvenerati** [caarlos0/dotfiles.zsh#334]
Hey maybe this is just my misunderstanding of rebase and merging but my fork of your dotfiles are constantly in a state of rebase. Again, I don't have any experience with rebasing and merging so if there are any tips to avoid or handle these when auto updates happen I would appreciate it. 

Love the work you've done with these dotfiles!

**Comment by caarlos0** [comment]
hey @insuusvenerati 

so, the autoupdate is intended for people using this fork directly... if change managed files you will eventually have merge problems...

did you take a look at the customisation doc? https://github.com/caarlos0/dotfiles/blob/master/docs/PERSONALIZATION.md

I think most things should be change-able without having to fork at all :) 

<blockquote><img src="https://avatars1.githubusercontent.com/u/245435?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/caarlos0/dotfiles">caarlos0/dotfiles</a></strong></div><div>dotfiles - Config files for ZSH, Java, Ruby, Go, Editors, Terminals and more.</div></blockquote>

**Comment by insuusvenerati** [comment]
Hmm. I forked cause I don't want to have to make changes every time I re setup my computer. Which is often. I'll just disable the autoupdate for now. It can probably be re worked to to work on forks. I'll do a PR once I finally git gud with shell scripts :P
