### ISSUE TITLE
Error when running ./script/bootstrap

### ISSUE THREAD

**Issue by gabbanaesteban** [caarlos0/dotfiles.zsh#342]
It starts to create all the symlinks and stuff but once it downloads antibody and try to update it fails.

`
antibody: git update failed for /home/vagrant/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-caarlos0-SLASH-ports Unknown option: -C
`
<img width="1534" alt="screen shot 2018-06-27 at 7 43 12 pm" src="https://user-images.githubusercontent.com/11374198/42005495-cb30e662-7a42-11e8-8dc1-3358c71b5264.png">

**Comment by caarlos0** [comment]
Hi @gabbanaesteban, can you paste the output of `git --version` please?

**Comment by gabbanaesteban** [comment]
Thanks for quick reply.
The output is:
```
git version 1.8.3.1

```

**Comment by caarlos0** [comment]
yeah, this is a very old version of git...

maybe we should work on not depending on git at all, but for now, if you can, please upgrade to a newer git version...

**Comment by gabbanaesteban** [comment]
I have updated my git version.

Now:
```
git version 2.18.0
```

Still getting the same errors.

*More info:*
-CentOs 7
-A user without root permissions.

**Comment by caarlos0** [comment]
2.18 is the version I'm using as well... weird..

can you paste `git --help` output here as well?

**Comment by gabbanaesteban** [comment]
`git --help`:

<img width="831" alt="screen shot 2018-06-28 at 2 21 17 pm" src="https://user-images.githubusercontent.com/11374198/42053688-38906384-7ae0-11e8-8773-94b4b32e73fe.png">

**Comment by caarlos0** [comment]
`-C` option is there.

Either your PATH is wrong and antibody is getting another version of git for some reason, or it's another error...

**Comment by gabbanaesteban** [comment]
You are right.
When I run `git --version` or any commands, it executes the 2.18.0 one, but for some reason, when I run the bootstrap file, it calls the other one.
