### ISSUE TITLE
Running fonts/install.sh fails

### ISSUE THREAD

**Issue by insuusvenerati** [caarlos0/dotfiles.zsh#345]
Install Fonts script fails on Ubuntu 18.04 with error `cp: cannot stat '/tmp/FiraCode/*.ttf': No such file or directory`

I know what the problem is. Gonna work on a PR if that's ok.

**Comment by caarlos0** [comment]
sure, thanks!

**Comment by caarlos0** [comment]
fixed in https://github.com/caarlos0/dotfiles/pull/346
