### ISSUE TITLE
Personalize vscode settings

### ISSUE THREAD

**Issue by tonythere** [caarlos0/dotfiles.zsh#348]
I want to custom some vscode settings (such as `editor.lineHeight`, `font`, etc). But any change will be tracked in git. Is there a way to personalize vscode settings like `~/.zshrc` approach.
Thanks

**Comment by caarlos0** [comment]
vscode does not have a way to include an extra file... so, unfortunately, no :/

**Comment by tonythere** [comment]
Thanks
