### ISSUE TITLE
Slow launch at  linux(ubuntu 18.04 based distros)

### ISSUE THREAD

**Issue by eamirgh** [caarlos0/dotfiles.zsh#350]
It takes about two seconds to get ready to use on Ubuntu 18.04.1 and KDE neon 5.15.
I've tested both on fresh install of OS without any modifications.

**Comment by caarlos0** [comment]
i tested on ubuntu 18 on docker and it seems fine... no idea what may cause this on your end...

**Comment by eamirgh** [comment]
I had installed it on a very first ubuntu 18.04 it used to work fine.
Could you please try it on vm? I tried to get the reason by removing .localrc or even .bashrc files but none of them was the problem. is there any way to listen and log what does make it?

**Comment by caarlos0** [comment]
sorry, I don't have free time to debug that right now

you can make sure you're using the latest zsh version and that you don't have extra things in your profile and etc... 

other than that, sorry, but will not look into this.
