### ISSUE TITLE
After type in `git commit -` the terminal will crash.

### ISSUE THREAD

**Issue by shanoaice** [caarlos0/dotfiles.zsh#351]
*As the title.*

In addition, this would happen even if you paste this inside the terminal.
This ***would not happen*** in pure zsh.

Error Message: `zsh: segmentation fault (core dumped)`

**Comment by caarlos0** [comment]
does not happen here.

which version of git and zsh you're using? which OS?

**Comment by shanoaice** [comment]
Ubuntu 18.04 on WSL, but I may not get my zsh version because I just rolled my Windows 10 version back and I lost almost everything. I thought my zsh version is the latest on Ubuntu software archive.

**Comment by shanoaice** [comment]
The only modifications I do is install rvm and add a lazy-loaded nvm. Maybe it's cause by rvm because I heard that rvm would modify `cd` command.
