### ISSUE TITLE
When are update.sh run?

### ISSUE THREAD

**Issue by hmbrg** [caarlos0/dotfiles.zsh#353]
Is there any mechanism in place for running `update.sh` files automatically or are they supposed to be run manually?

If true, wouldn't it make sense to run them inside the auto-updater?

**Comment by caarlos0** [comment]
its supposed to be in your user's crontab, you can check it with `crontab -l`

**Comment by radum** [comment]
@hmbrg At bootstrap the install from [here](https://github.com/caarlos0/dotfiles/blob/master/autoupdate/install.sh) is run and doing so is running the crontab for the updates.

**Comment by caarlos0** [comment]
I think this is cleared now, will close the issue :) 
thanks!
