### ISSUE TITLE
Scripts permissions

### ISSUE THREAD

**Issue by radum** [caarlos0/dotfiles.zsh#354]
Hello,

First of all thank you for sharing this repo, it is a great source of learning.

I was wondering how do you deal with running permissions? When you run the bootstrap script without using source or sh before it will complain for permissions, and if you do run it with source or sh it will fail while the other scripts are run.

How do you run it and deal with permission issues? Do you chmod the scripts?

Thank you

**Comment by radum** [comment]
I think you pushed all files that need to run using chmod -x permissions right? So when you clone down the repo that is kept and will just work.

**Comment by caarlos0** [comment]
> I think you pushed all files that need to run using chmod -x permissions right? So when you clone down the repo that is kept and will just work.

yep, git will keep the permissions of the files.

you can test it with something like this:

```
mkdir test && cd $_
git init
touch foo
git add foo
chmod +x foo
git status -sb
```

it should show that the file was modified:

```
## No commits yet on master
AM foo
```

hope it helps :)
