### ISSUE TITLE
Travis issues

### ISSUE THREAD

**Issue by radum** [caarlos0/dotfiles.zsh#355]
I was wondering if you have build this recently with Travis. I have a few issues when I run my version of it.

1. Mac build returns an error in Travis around the rate limiting:

```
$ make ci
curl: (22) The requested URL returned error: 403 rate limit exceeded
Unable to get caarlos0/shcheck version.
curl: (22) The requested URL returned error: 403 rate limit exceeded
make: *** [check] Error 22
The command "make ci" exited with 2.
```

2. Building on linux fails because the VIM install.sh does something that fails all subsequent install.sh files. For example if I create a install.sh in zsh that only does this: `mkdir -p "$HOME"/.logs` it will not run because VIM install fails for some reason, and I can't tell why from the logs. Running it manually does the same thing without a trace. I think is how vim-plug works but not sure.

I also think your vim config file using vim-plug has a dependency on having go installed? Am I right?

3. Even if I remove the VIM install Travis fails with a wrong exit code from the make file.

```
› registering last update
  [ OK ] dependencies installed
  All installed!
sourcing ~/.zshrc
Makefile:12: recipe for target 'ci' failed
make: *** [ci] Error 1
The command "make ci" exited with 2.
```

**Comment by caarlos0** [comment]
should be fixed.
