### ISSUE TITLE
iTerminal will resume settings when I open it next

### ISSUE THREAD

**Issue by tickmao** [caarlos0/dotfiles.zsh#356]
well, iTerm will resume settings when I open it next, So I had to set profiles when I opened it at first. what can I do to solve it?

**Comment by caarlos0** [comment]
Sorry, I don't quite get what is happening... can you elaborate?

**Comment by tickmao** [comment]
Because I will lose the iTerm profiles what I had set, sometimes later there are only the default profiles. The iTerm preferences will be reset.

**Comment by caarlos0** [comment]
I still dont understand what the problem is.


closing
