### ISSUE TITLE
_z_dirs error shows up randomly

### ISSUE THREAD

**Issue by ghost** [caarlos0/dotfiles.zsh#358]
Good hello there,

I'm facing with an issue that makes me think that my configuration messed up. The problem is probably because of `z.sh` plugin. Here's the exact demo of the error.

```bash
λ cd .dotfiles
_z_dirs:2: no such file or directory: /Users/my_username/.z
```

I've already checked the `zsh_plugins.sh` and the line that loads the `z.sh` exists.

**Comment by caarlos0** [comment]
this is probably an issue with the z plugin itself... I recommend checking https://github.com/rupa/z

<blockquote><img src="https://avatars2.githubusercontent.com/u/46809?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/rupa/z">rupa/z</a></strong></div><div>z - jump around. Contribute to rupa/z development by creating an account on GitHub.</div></blockquote>
