### ISSUE TITLE
~Perhaps~ zsh-users/zsh-completions isn't working

### ISSUE THREAD

**Issue by oieduardorabelo** [caarlos0/dotfiles.zsh#71]
I was using `brew` and I forgot a command, then, I tried to use &lt;tab&gt; to autocomplete the command and I realized that it was not working

Looking at [zsh-completions](https://github.com/zsh-users/zsh-completions) official repository, they recommend to use:

> If you're using antigen, just add **`antigen bundle zsh-users/zsh-completions src`** to your .zshrc where you're loading your other zsh plugins.

[The current implementation](https://github.com/caarlos0/dotfiles/blob/master/antigen/bundles.txt#L7), doesn't have the **src** in the final,

So, I recommend you to check if any other autocomplete command are working (far from git/npm or any other command do you load a custom autocomplete function)

[I fixed it for my dotfiles](https://github.com/oieduardorabelo/dotfiles/blob/master/antigen/bundles.txt#L7), I just didn't did a PR because I don't know if is a problem in your env

**Comment by oieduardorabelo** [comment]
actually, I don't know how to test the autocomplete for the others packages,

if you figure out how, let me know! :baby_chick:

**Comment by caarlos0** [comment]
@oieduardorabelo you're right!

Fixed in #72

Many thanks :beers:
