### ISSUE TITLE
Docker Prompt

### ISSUE THREAD

**Issue by j-walker23** [caarlos0/dotfiles.zsh#83]
Hey man. First, this is awesome. Thank you! For hours i have been reading your stuff and copying plugins/code etc.

Wish  i would have seen it sooner, i just got done with a pretty long process of holman's files with antigen. First time with any of this stuff.

I stumbled across your stuff and it seems to just add even more stuff that i would want. Docker has been on my list to learn and i saw your part about using docker so it was perfect.

My question has to do with the prompt. Should i be able to see the cool pure prompt when running in docker? Right now i just see something like std `root@248b393ac23f:`.

I did get a few errors while running it which is why i wanted to ask what was expected.
I got this a lot on first docker run

```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype

antibody:1: exec format error: /root/.dotfiles/antibody/antibody/antibody
antibody:3: no matches found: /*.plugin.zsh
```

**Comment by caarlos0** [comment]
Hi @j-walker23,

so, about the pure prompt inside the docker container: no, you should not. This happens because the container is "like a vm", so it is a new user, shell and everything else, without the pure prompt installed.

About the errors, I'm checking here in a new installation to see if I figure out what is going on...

Oh, hey, many thanks for the feedback :beers:

**Comment by caarlos0** [comment]
hey @j-walker23 , I wasn't able to reproduce this problem (but found others :8ball: ), can you paste here the result of `uname -a`, please? Thanks!

**Comment by j-walker23** [comment]
Oh ok. Thanks for explaining that. Guessing its something i should already know lol.

Result is `Darwin john 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64`

And you are welcome, this has been a lot of fun.

**Comment by caarlos0** [comment]
Oh, now I see it...

you are executing the dotfiles as root?

no need to that..

do this:

``` sh
$ sudo rm -rf /root/.dotfiles
$ rm -rf ~/.dotfiles # or mv if you want a backup for any reason
$ bash -c "$(wget -O - https://raw.githubusercontent.com/caarlos0/dotfiles/master/script/install)"
```

This should fix the issues... let me know if it doesn't, please :beers:

**Comment by j-walker23** [comment]
I might have been in root when i did it within the docker. Can't remember, first time in docker. So much to learn!
The `uname` result i gave was from my own terminal, probably should have mentioned that.

On another note i decided to just backup my current .dotfiles and install yours with the command you gave me.
Just as a fyi when it finishes the terminal and iTerm say

```
/Users/john/.dotfiles/antibody/path.zsh:source:2: no such file or directory: /Users/john/.dotfiles/antibody/antibody/antibody.zsh
/Users/john/.zshrc:18: command not found: antibody
/Users/john/.dotfiles/zsh/prompt.zsh:5: command not found: antibody
/Users/john/.dotfiles/zsh/prompt.zsh:6: command not found: antibody
```

Seems that antibody didn't install. I just went into `$ZSH/antibody` and ran `source install.sh` and it seemed to install right.

After iTerm reload it first says

```
Unable to find any JVMs matching version "1.8".
panic: exit status 128

goroutine 1 [running]:
main.Bundle(0x7fff5fbffaf0, 0x12, 0x2081ec020, 0x16)
    /Users/carlos/Code/Go/src/github.com/caarlos0/antibody/api.go:15 +0xe1
main.ProcessArgs(0x2081d8010, 0x2, 0x2, 0x2081ec020, 0x16)
    /Users/carlos/Code/Go/src/github.com/caarlos0/antibody/api.go:42 +0x116
main.main()
    /Users/carlos/Code/Go/src/github.com/caarlos0/antibody/main.go:9 +0x12e
antibody:3: no matches found: /*.plugin.zsh
```

I have not seen that again now it only says when starting new shell.
`Unable to find any JVMs matching version "1.8".`

Is that the jvm plugin? I only have a need for 1.7 at the moment, probably just need to configure that somewhere.

Anyway, i am not blocked or anything. I just wanted to give you a heads up on what i was seeing.

Thanks again for this, lots of fun!

**Comment by caarlos0** [comment]
hmm, run `jvm global 7`, should fix this. Will fix that in JVM as well...

btw, `antibody` should have been installed, will check that too

**Comment by caarlos0** [comment]
@j-walker23 please, do a `antibody update`. Thanks!

**Comment by caarlos0** [comment]
or just run `dot`

**Comment by j-walker23** [comment]
Will do, thanks man!

**Comment by caarlos0** [comment]
Thanks! :beers:
