### ISSUE TITLE
just a reminder to reach prompt λ 

### ISSUE THREAD

**Issue by erson** [caarlos0/dotfiles.zsh#85]
To reach the prompt λ; you have to install oh-my-zsh before installing this dotfile.if you forget to install oh-my-zsh after installing this dotfile you can still install it.It is copying the .zshrc file to .zshrc.(backup-this string is something that i cant remember now). just move it on new .zshrc 

move zshrc.(backup-this string is something that i cant remember now) .zshrc

it will work.

it could be integrated in base installation.that will be much better.

**Comment by caarlos0** [comment]
no, you don't need oh-my-zsh to install this dotfiles... 

Sorry, but I don't understand what is your point with this issue...

**Comment by erson** [comment]
![screen shot 2015-06-14 at 01 20 17](https://cloud.githubusercontent.com/assets/1500710/8146161/8ddb5646-1233-11e5-99b3-c41585569dc0.png)

to seeing the prompt at screenshot you have to install zhs+oh-my-zsh.and if you try to install this dotfiles on terminalapp the terminalapp(osx buit-in) window is closing to apply theme.i overcome this situation with installing iterm2 and started dotfiles installation on it.so the installation progress is ended as it is needed(it is not closing iterm2 window).I have also forgetten to install oh-my-zsh(it is not coming with base installation of this dotfile/install like iterm2) and after installation i have reopened iterm2 but my prompt was (user@user : /User/user smth like this...) so i installed oh-my-zsh and did the thing i have said before.

anyway this is a great dotfile i have ever find. and im making some changes on it to suit my needings(started using home and work).thank you for your work.those things that im mentioned are problems i have faced while  trying to install this.i have solved them.i hope these will help others.
im using yosemite 10.10

**Comment by caarlos0** [comment]
Probably you just forgot to `chsh -s /bin/zsh`...

Installing oh-my-zsh is absolutely not necessary. See the Dockerfile in the project root, for example..

About the default Terminal.app closing, I'll take a look. Thanks!
